version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/docker
    overwrite: true

hooks:
  # BeforeInstall:
  #   - location: scripts/cleanup.sh
  #     timeout: 300
  #     runas: root
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
